### ISSUE TITLE
最大画像サイズを取得するobj.getinfo

### ISSUE THREAD

**Issue by karoterra** [ePi5131/lua_aviutl_definitions#2]
最大画像を取得するときの `obj.getinfo()` について `name` に渡すのは `"max_size"` ではなく `"image_max"` だったりしますか？

https://github.com/ePi5131/lua_aviutl_definitions/blob/5ee3baebc86df29c2217497cd9d9d30ce86c32ee/exedit.lua#L813-L818

**Comment by ePi5131** [comment]
はい…
